resolution = [240, 67]
font = "resource/font/SarasaTermCL-Regular.ttf"
font_bold = "resource/font/SarasaTermCL-Bold.ttf"
is_force_skipable = false
save_dir = "save"
gallery_dir = "resource/gallery"
about_file = "resource/about.txt"
entre_script = "resource/script_example.fss"
default_bg_img = "resource/bg_0.png"
default_face_img = "resource/default_face_img.png"
preprogress_script = ["resource/script_example.fs"]
max_history_ls = 60
mainmenu_default_bg_img = "resource/main_menu_bg.png"
mainmenu_default_bgm = "resource/A Journey Awaits.ogg"
mainmenu_session_bg_map = []
